name: Build and publish image to DockerHub

on:
  push:
    branches:
      - master
      - dev-master
    paths:
      - .github/matrix.json
      - .github/workflows/publish-image.yml
      - 'docker/**'

jobs:
  setup:
    uses: kyzima-spb/gh-actions/.github/workflows/read-matrix.yml@master
    with:
      path: ./.github/matrix.json
  
  build:
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      matrix: ${{ fromJSON(needs.setup.outputs.matrix) }}
    steps:
      -
        name: Check Out Repo
        uses: actions/checkout@v4
      -
        uses: kyzima-spb/gh-actions/.github/actions/docker-build-image@master
        with:
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          context: ./docker/root
          file: ./docker/Dockerfile
          images: |
            ${{ vars.IMAGE_NAME }},enable=${{ github.ref_name == 'master' }}
            {ghcr},enable=${{ github.ref_name == 'dev-master' }}
          build-args: |
            PYVERSION=${{ matrix.pyversion }}
            RELEASE=${{ matrix.release }}
          tags: |
            ${{ matrix.pyversion }}-${{ matrix.release }}
          flavor: |
            latest=${{ matrix.latest }}
          cache: |
            arg=default,namespace=${{ secrets.DOCKER_HUB_USERNAME }},repo=buildcache,version=sphinx-${{ matrix.pyversion }}-${{ matrix.release }}
          # push: ${{ github.ref_name == 'master' }}
          docker-username: ${{ secrets.DOCKER_HUB_USERNAME }}
          docker-password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
      # -
      #   name: Build and push
      #   uses: docker/build-push-action@v5
      #   env:
      #     IMAGE_VERSION: ${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
      #   with:
      #     cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/buildcache:${{ env.IMAGE_NAME }}-${{ env.IMAGE_VERSION }}
      #     cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/buildcache:${{ env.IMAGE_NAME }}-${{ env.IMAGE_VERSION }},mode=max
